* We all know that pot-bellied feeling. It’s not pleasant, especially when you have a tight dress to fit into. Girls, you know what I’m talking about. There’s no fun in spending your evening refusing to exhale in order to avoid being asked, ‘so when are you due?!’ But fear no more, this article is here to help you (and me), beat belly bloating. I bring you the top 12 foods to stop bloating and gas.
 - Top Foods to Beat Bloating and Flatten Your Stomach
 1. Papaya - Papaya is not only a delicious exotic fruit, it also helps to relieve bloating. The clever papaya, also referred to as the ‘fruit of the angels,’ by Christopher Columbus, contains many active compounds that combat belly bloating. One of the main reasons papaya can help flatten your tummy is because it contains papain, a protein-digesting enzyme. It is worth noting that green unripe papaya (which is more available in Asian food stores), contains more papain than ripe papaya. So why not pop some papaya on top of your salad for a fruity kick? Your future flat stomach will thank you.
 2. Pineapple - Pineapples have long been used to treat digestive disorders, such as bloating. There is a clever little enzyme in pineapples, known as bromelain. It is thought to aid digestion by breaking down proteins in the stomach which can help to relieve abdominal bloating. If you don’t like pineapple, then you can always take bromelain in concentrated tablet form. But before taking any supplements, make sure you to talk to your doctor and check the label for the recommended dosage and for possible side-effects. You can also try this delicious digestive detox smoothie which is one of my favorites.
 3. Avocado - This superfood, avocado, is here to rescue your tummy. Avocado contains the digestive enzyme lipase, which breaks down fat and gets food out of your digestive tract to prevent gas and bloating. It’s high potassium content also helps you eliminate water. There are many ways to reap the benefits of this fabulous fruit. Why not slice it up on toast with a sprinkle of salt and pepper on top, whiz it up into smoothie or it enjoy as part of a fruit salad.
 4. Ginger - Ginger is an effective carminative, (a carminative is a fancy word for a herb that helps to soothe the digestive tract and relieve gas). Ginger medicinal benefits also include thinning of the blood and improving circulation, which helps to relieve bloating. Ginger can also provide effective pain relief which makes ginger useful for easing abdominal pain that is often associated with bloating. To get the best out of ginger, why not make a fresh ginger tea? Alternatively, ginger is a great ingredient to add to dishes for a zesty kick.
 5. Apple Cider Vinegar (ACV) - Apple cider vinegar may not smell particularly inviting, but once you know that it is a hero for curing bloating, you may be more inclined to hold your nose and sip on the stuff. Just make sure you buy a good quality bottle of organic, unfiltered, unpasteurized, and unprocessed ACV. The refined stuff isn’t going to cut it. Look out for the stringy, filmy material floating in the bottle – this material, called the mother, is good bacteria that creates the vinegar. But before you go downing a bottle neat, it is worth knowing that the best way to consume apple cider vinegar is to dilute it with water (1 tablespoon with a glass of water), and drink it before a meal, to reduce bloating afterwards.
 6. Yogurt (probiotic-rich foods) - Probiotics are strains of bacteria that regulate your body’s digestive system. The good news is that yogurt contains probiotics and eating the stuff on a daily basis has been shown to ease bloating by up to 78 percent, according to a study from the University Hospital of Southampton. Look out for yogurts with the label “contains live and active cultures,” as they are full of bacteria that will improve your digestion. If you want to get rid of bloating – eat yogurt!
 7. Oats (fiber-rich foods) - Fiber-rich food such as oats relive bloating bloating and constipation by bulking up stool. This makes bowel movements easier to pass and then there is less chance of gas build up in the digestive system. However, go easy on the fiber at first. If you eat too much, it could backfire and you may end up producing too much gas and then it’s hello, big, bloated belly. So introduce fiber into your diet slowly and incorporate it into a balanced diet.
 8. Bananas (potassium rich foods) - Bananas are a nifty fruit. The potassium inside them actually helps to ease bloating caused by salty food. You see, salt draws fluid into the cells, and potassium draws the water molecules out of the cells. When you choose a banana to snack on, just be sure to pick a ripe one, as the unripe ones contain resistant starch which can produce wind and cause bloating.
 9. Water with Lemon - A lot of people are put off drinking water when they feel bloated as they believe it will add to the problem. However, when you are experiencing water retention, your body is holding on to that fluid so that you don’t dehydrate. Therefore, it is actually a good idea to drink water to push the fluid out. Lemons are a very healthy addition to water and aid a large number of digestive problems including helping the bowel to dispose waste, cleanse the liver and prevent constipation.
 10. Watermelon - The clues are in the name with this one. As watermelon is a water-dense food, (containing 92% water), this fruit, along with other delicious melons, such as cantaloupe and honeydew, are natural diuretics, which cause you to pee out excess water and salt. Melons also contain potassium, which as we learnt earlier, help to get rid of sodium.
 11. Asparagus - Asparagus is here to de-bloat you. Sure, it makes your pea smell funky, but it also makes you want to pee, thus getting rid of all that excess water and relieving your bloated belly. Asparagus is also made up of probiotics, which as we know from earlier, are fab for encouraging the growth of good bacteria. This all makes for a lovely, healthy digestive system that is free from too much gas.
 12. Herbal Teas - There are certain herbs that are known to improve digestion, such as chamomile, lemon balm and peppermint which you can prepare as herbal infusions. So if you don’t want to feel heavy after a meal, it is recommended to drink herbal infusion to improve digestion. You can find more information about these herbs in my previous article about the top 10 herbal teas that
 ---------------------------------
* The world around us seems to demand constant stimulation at times. We’ve evolved as animals with a very simplistic lifestyle, into a complex society of media and communication. Before the technological and mechanical innovations of our modern age, our ancestors used to actually sleep about 12 hours a day, in two separate chunks [1]. But the notion of that much sleep seems absurd in modern society – we’ve got work to do and social lives to attend to. Now, on average, humans get approximately six to eight hours of sleep every 24 hours. The problem with how we’ve developed as a species is the creation of insomnia. Many times we find it extremely hard to fall asleep due to a restless mind and in this post I will give you a few simple tips and tricks that will help you to fall asleep even when your mind is racing.

	Why Does Insomnia Exist?

	Sure, insomnia can be due to medical conditions, aging and diet – but it’s also commonly developed from factors of modern living [2]:

	Anxiety and Stress from social lives, dramatic events and demanding work schedules
	Depression that comes from unbalanced sleep schedules, the above-mentioned factors for anxiety and stress, and as a side effect of certain medications
	Prescription drugs given to people to alleviate depression, unbalanced blood pressure, allergies and ADHD
	Substances that are consumed socially and personally such as coffee, tobacco, alcohol and drugs
	Insomnia is a difficult condition to cope with – be it temporary or a recurring issue. The National Sleep Foundation (NSF) states that polls revealed almost 60% of adults ages 18 to 29 having some type of insomnia, contradicting the notion that the disorder is more common in old age (only 44% of people older than 65 reported signs of insomnia)[3]. Because a balanced sleep schedule is so important to our overall health, it is worth the effort to overcome insomnia and return the body to a balanced sleep schedule.

* Tricks to Fall Asleep When You Mind Is Busy
  - We’ve all experienced it at one point or another. You toss and turn in your bed with darkness around you, while your body is exhausted from the same busy day that is making your brain protest the notion of rest. People don’t have to be condemned to a life of unbalanced sleep in today’s society however. There are several ways to hit the kill switch and enter dreamland at the end of a long day.
	1. Create a Relaxing Pre-bed Routine - The time leading up to bedtime is often hectic, so when people finally get their head to hit the pillow, their brains and bodies are still pumping at full power. Preparing yourself for sleep ahead of time and allowing your body to chill out before sleep will make a restful night much easier. Some people recommend taking at least an hour of your time, more can’t hurt, to easing yourself to sleep.
			What you do during this time is completely dependent on your own preferences. Some people enjoy mild body relaxing exercises such as stretching, yoga or meditation. Others sit down with a cup of chamomile tea and listen to mild music. Many read books, as they tend to prepare your brain for the fictional world of dreaming while pulling people from the stressful outside world. Whatever it is that relaxes you, give it a try and monitor how sleep improves.
	2. Monitor Substance Intake - Sometimes it’s our seemingly harmless daily habits that deprive us of a restful night. Caffeine is of course one of the top contributors to insomnia. If you drink coffee or any other drink with moderate to high caffeine levels in the evening, it could likely prolong your brain’s awakeness through the night. Try to limit yourself and set a cutoff time for caffeine if you think it might be affecting your sleep. You can drink water to flush your body or try foods with tryptophan, an amino acid that makes you sleepy (drinking water will also help you flush fat – check my fat flush water recipes).  To get more information about foods that will help you get better sleep -read my post the best foods to get better sleep.
	3. Live in the Now - In a modern society we tend to live in constant preparation for the future. This is one of the most simplistic yet harrowing contributors to sleep loss. Thinking constantly about what will happen next stirs up anxiety and stress that keeps people in a state of sleepless worry. This can happen from both positive and negative perspectives. The question many people are asking themselves is how to fall asleep when you have things on your mind.
						 A positive perspective would be exemplified by an excited child on Christmas or the day before their birthday. They’re often so excited that it’s hard for them to catch any Z’s. A more common and stressful perspective is the negative outlook on a demanding millennial age life. Try not to obsess about what the next day has to hold. It seems easy to do but becomes strangely difficult in a world where we’ve become dependent on a prepared mindset for success. Find some way to busy your mind by observing the immediate moment rather than fixating on the future. Try counting sheep, listening to sounds of nature, or even reminiscing older memories – as long as they aren’t stressful memories of course.
						 Another common suggestion is to write on a piece of paper a list of all the things that need to be done for tomorrow or the next few days in order of importance and plan your schedule. This will ease your mind and will better enable you to sleep. If it is obvious that your mind is active and you can’t sleep, then get up and go into another room and sit in dim light, doing something calm and relaxing. The act of getting up and out of bed can help to stop those running thoughts, as lying in bed with a busy mind teaches the body that the bed is a place to continue to be awake and think, and this is what we want to avoid.
						 There are plenty of different contributors to sleep loss and deprivation, more often than not they are preventable with the right habits. If you experience persistent sleep loss and can’t seem to figure out why, it’s worthwhile to visit your physician and check for underlying medical causes. But before you do that, try a few of the aforementioned tricks for getting better sleep and see if they shut your brain down at the end of a long and stressful day.
------------------------------------
* Coconut oil can not only add magic to your dishes, but its uses go way beyond your kitchen table. Give into the coconut hype and try one of these everyday uses for coconut oil and be amazed by the results:

	1. The Healthiest Oil For High-Heat Cooking - Coconut oil is the best oil for cooking. Its small medium chain saturated fatty acids are easily metabolized into energy and are less likely to be stored as fat. It boosts metabolism, is heart-friendly, and improves digestion. Click here to read my previous article: Discover the Truth About Coconut Oil and Its Many Health Benefits
	2. Oil Pulling With Coconut Oil Can Transform Your Oral Health - Have you ever tried to pull oil to improve your oral health? It is super easy and can help you to reduce bad breath, harmful mouth bacteria, and gingivitis. It whitens your teeth and promotes pink and healthy gums.
																	 The only thing you need to do is swish 1 tablespoon coconut oil around in your mouth for about 15-20 minutes. DONT SWALLOW any of the oil as it is packed with bacteria and waste materials. Spit out the oil and brush your teeth afterwards. To avoid clogged drains make sure to spit the oil out in the trash can instead of your sink. The first few times your gag reflex may kick in, so start with 5 minutes and build your way up.
	3. Condition Your Hair With Coconut Oil - Depending on the length of your hair, heat 3 to 5 tablespoons of coconut oil until completely melted. Massage the oil into your hair and scalp. Cover your hair with a towel, shower cap, or plastic wrap. Let sit for at least 1 hour or overnight. The longer you wait the better your hair will be conditioned. Wash your hair with shampoo for 2 to 3 times. Your hair shouldn’t feel greasy after washing. Let it air dry and be amazed by the shiny, soft look. This also helps to treat dandruff.
	4. Hydrate Your Body - Coconut oil is a natural moisturizer and has antibacterial properties to soothe dry skin. It can even help you to reduce skin infections like acne, psoriasis, and eczema. It is often used in commercial and DIY body lotions, but it can be used on its own as well. A spoonful is usually enough to cover your whole body.
	5. All-Natural Aftershave - For a silky smooth finish after shaving, rub pure coconut oil onto your skin.
	6. Dry Chapped Lips - Most DIY lip balms contain coconut oil for its antibacterial and moisturizing effect. Not much of a DIY’er? No worries, just rub pure coconut oil onto your lips, repeat as much as needed. Click here to get my favorite lip balm recipe: How to Make Your Own Natural Lip Balm for Smooth, Kissable Lips
	7. Soothe Burns, Bruises, Or Insect Bites - Coconut oil speeds up healing, stops itching, reduces swelling, reduces scarring, and stops burning sensation. Apply pure coconut oil on the affected area a few times a day until healed.
	8. Coconut Oil Feet Care - Pure coconut oil works wonders to treat dry, cracked heels or feet. Apply on your feet after a shower, put on some old socks to cut off the air and leave on overnight.
	9. Mild Sun Protection Or After-Sun Soother - Coconut oil has a natural SPF of about 5 to 7. It helps to hydrate, soften, and nourish your skin. Works great to treat sunburns as well.
	10. Make-up Remover - Gently wipe the eye area with a cotton swab and a dab of coconut oil to remove even the toughest water-proof mascara.
	11. Massage Oil - Coconut oil is a good base oil for massage. Warm up a bit of coconut oil and add a drop or two of your favorite essential oil for a nice fragrance and added health benefits.
	12. Cheekbone Highlighter - To highlight your cheekbones, apply a small amount over your make-up and be amazed by the effect.
	13. Diaper Rash - To improve your baby’s skin health, apply as much as needed on the affected areas.
	14. Prevents Stretch Marks - Apply coconut oil a few times each day to keep your stretching skin moisturized and prevent stretch marks.
	15. Homemade Deodorant - Coconut oil can be used as an all-natural deodorant. Click here to get the recipe. If you want to make it travel-friendly, add beeswax for a firmer consistency and pour in an old, clean deodorant stick.
							 These were my favorite uses, but coconut oil is actually such a versatile oil that it can be used for so much more. It can be safely used for your babies, kids, and furry friends. Some people even use it to lubricate guitar strings or clean bronze or metal items.
-----------------------------
* While inflammation is a natural protective mechanism and repair of the body to overcome tissue injury, allergy or ongoing stress, in chronic conditions the body keeps trying unsuccessfully to turn off the inflammation. Chronic inflammation is nowadays linked to many diseases and is known for worsening their symptoms. One explanation is that inflammation causes the process and accelerated aging, as well as increases the risk of coronary diseases, strokes and cancer. The inflammation causes accelerated erosion and rifts within the body by increasing oxidative activity. Sometimes it is not easy to find all the causes of inflammation, but it’s easier to use available foods in every home to reduce inflammation without the heavy price the body pays for prolonged use of drugs. You can do this by making this tea or the smoothie below to add anti-inflammatory foods to your menu.
	-Berries
		Berries contain polyphenol compounds claimed to have anti-inflammatory activity in humans. Among the most notable polyphenols in berries are anthocyanin’s, that are responsible for their distinctive colors of red, blue, and purple. Berries have been studied widely for their antioxidant properties, and preclinical data suggest important effects on inflammatory processes in the body.
	-Dark Leafy Greens
		Low magnesium level has been associated with numerous pathological conditions characterized as having a chronic inflammatory stress component. One of the best food sources for magnesium are dark leafy greens (like kale and spinach). Kale, spinach and other leafy greens also have high concentrations of vitamins that fight disease. Specifically vitamin E that has anti-inflammatory properties. The other antioxidants that are found in dark leafy greens are important components of an inflammation-fighting diet.
	-Ginger
		If you suffer from arthritis pain in the knees, consuming ginger on a daily basis can definitely help. Ginger contains powerful anti-inflammatory substances called gingerols. These have been tested in various research of rheumatic diseases such as osteoarthritis or rheumatoid arthritis. The participants in the studies reported a gradual reduction of pain, improving agility and movement and reduction in swelling when using ginger regularly.
	-Coconut oil
		The lauric acid in coconut oil has anti-inflammatory properties, a study in the February 2010 issue of “Pharmaceutical Biology” found virgin coconut oil — which is processed at low heat without chemicals — reduced ear and paw swelling in rats, while also inhibiting chronic inflammation. In another research, researchers extracted the antioxidants unique to virgin coconut oil from the oil and injected them into rats with induced arthritis. They found that the unique coconut oil antioxidants reduced inflammation associated with arthritis more effectively than current pharmaceutical drugs.

	These very nutritious seeds are high in omega-3 fatty acids, which are responsible for metabolic processes that help fight inflammation. According to the University of Maryland Medical Center, Research shows that omega-3 fatty acids reduce inflammation and may help lower risk of chronic diseases such as heart disease, cancer, and arthritis. If you cannot find chia seeds, use ground flaxseed or walnuts instead.
	- Green tea
		The main polyphenol in green tea is called epigallocatechin gallate (EGCG). Scientific studies suggest that EGCG and green tea polyphenols have anti-inflammatory and anticancer properties.

	Anti inflammatory smoothie
		1 cup berries of your choice (such as blueberries, raspberries, cranberries)
		1 compressed cup of leafy greens of your choice (such as kale, spinach)
		2 inch (5 cm) piece of ginger
		1 tablespoon unrefined coconut oil
		1 teaspoon, or more, of fresh chia seeds Green tea

		A little bit of honey, maple syrup, or stevia to sweeten

		Directions
			Put all ingredients in a blender (add green tea according to your desired consistency). Drink immediately to enjoy the most nutritional benefits.
-----------------------------
* Did you know that you can live a pretty normal life with only 20% of your kidney function? That is why a steady decline and gradual damage to your kidneys can often go unnoticed for a long time. Sometimes, even common habits can cause damage to your kidneys and when the problems are finally discovered, it can be too late. Our kidneys are an amazing organ. They produce hormones, filter blood, absorb minerals, produce urine and maintain a healthy acid-alkaline balance. There is no life without the kidneys, and the Chinese view them as the seat of essential life energy. Looking after your kidneys goes hand in hand with looking after your health and well-being. If you want your kidneys to thrive and serve you well for the foreseeable future, here is a list of habits you should avoid:
	1. The Sugary Soda Habit – A study carried out on employees at Osaka University in Japan suggested that drinking two or more soda drinks a day (diet or regular) may be connected with a higher risk of kidney disease. 12,000 employees were included in the study, and those that consumed larger amounts of soda were more likely to have protein in their urine. Protein in urine (proteinuria) is an early sign of kidney damage, but, when discovered at that stage, the disease can still be reversible.
	2. Smoking – Smoking has been linked to arthrosclerosis. The narrowing and hardening of blood vessels affects the blood supply to all vital organs, including the kidneys. According to the study published in Clinical Pharmacology and Therapeutics, two cigarettes a day are enough to double the number of endothelial cells present in your blood. This is a signal of arterial damage. Clinical Journal of the American Society of Nephrology cites many different studies conducted since 2003 which all link smoking to decreased kidney function.
	3. Vitamin B6 deficiency – A healthy diet is important for good kidney function. According to the studies performed at the University of Maryland Medical Center, vitamin B6 deficiency increases your risk of kidney stones. For optimal kidney function, you should consume at least 1.3 milligrams of vitamin B6 daily. The richest sources of this vitamin include fish, chickpeas, beef liver, potatoes and starchy vegetables, and non-citrus fruits.
	4. Lack of exercise – Exercise is another good way to protect your kidneys. A large study published in 2013 in the Journal of the American Society of Nephrology suggested that postmenopausal women who exercised had 31% lower risk of developing kidney stones. Generally speaking, maintaining a healthy weight will reduce your chances of kidney stones, so get moving.
	5. Magnesium deficiency – If you don’t get enough magnesium, calcium can’t get properly absorbed and assimilated, which can result in calcium overload and kidney stone formation. To prevent that, consume green leafy vegetables, beans, seeds and nuts. The mighty avocado is a good source of magnesium as well.
	6. Frequent sleep disruption – We all like a good night’s sleep. And so do our kidneys. Science Daily reports that chronic sleep disruption can cause kidney disease. According to Dr. Michael Sole, Cardiologist and founding director of the Peter Munk Cardiac Center and Professor of Medicine and Physiology at the University of Toronto, kidney tissue gets renewed during the night, so sleep interruptions can cause direct damage to this organ.
	7. Not drinking enough water – Our kidneys need to get properly hydrated to perform their functions. If we don’t drink enough, the toxins can start accumulating in the blood, as there isn’t enough fluid to drain them through the kidneys. The National Kidney Foundation suggests drinking at least 12 glasses of water per day. An easy way to see if you’re drinking enough is to check the color of your urine.
	8. Not emptying your bladder early – When nature calls, you should listen. Retaining urine in your bladder is a bad idea. If done on regular basis, it can increase the urine pressure in your kidneys and lead to renal failure or incontinence.
	9. Consuming too much sodium – Salt is important for the body, but you should limit your intake. Over consumption can raise your blood pressure and put too much strain on the kidneys. No more than 5.8 grams of salt should be eaten daily, so take it easy with that salt shaker.
	10. Consuming too much caffeine – We often consume more caffeine than we think we do. It features in many soft drinks and sodas, and before you know it, your blood pressure goes through the roof and your kidneys start complaining.
	11. Pain-killer abuse – Way too often we take medications too fast, in too big doses and not in the right way. When pain occurs, it’s so easy to just swallow the pill. But, you should think twice. All pharmaceutical drugs come with side effects, and many cause damage to the kidneys. Having said that, there are some drugs that you should be taking. See the next point.
	12. Missing your drugs – High blood pressure and type 2 diabetes are two very common conditions that are often brought on by our life style and unhealthy diet. If you already have them, be aware of the damage they can cause to your kidneys and protect your precious organs by taking the prescribed medications.
	13. Too much protein – According to Harvard University, too much protein in your diet can harm the kidneys. The by product of protein digestion is ammonia – a toxin your hard-working kidneys need to neutralize. More protein means more effort for the kidneys, which can, over time, lead to decreased function.
	14.  Not treating common infections quickly and properly – We are all guilty of sometimes ignoring simple colds and flu, and pushing our bodies to the brink of exhaustion. But that can cause kidney damage. Studies have shown that people who are reluctant to rest and heal properly, often end up with kidney disease.
--------------------
* Bread is a staple food in our diet and we just can’t get enough of this stuff, which is why leading fast food chains such as Subway are everywhere. You would think that you could just pick up a delicious sandwich at your convenience without having worry about a thing. But the reality is that there are some scary ingredients in our bread and many of these ingredients you didn’t know were in your bread. You may think that the bread you are eating from Subway is innocent stuff, but the pesky bread makers at the Subway HQ have been discovered to have been using a chemical called Azodicarbonamide. Oddly enough, the chemical is found in yoga mats and shoe soles. If you are thinking: “why on earth are they serving yoga mat bread?” It is because it strengthens the dough and adds elasticity. Yum.
  But don’t worry, as on February 2014 Subway said the ingredient will be removed from their bread. In a statement they said:
  “Even though this ingredient is safe, we are removing it from Subway bread. This process began last year and is nearly completed — we have already developed an improved bread formula, conducted extensive performance and consumer testing on it, and pending final government approvals we should complete the entire conversion process within the coming weeks. Azodicarbonamide is “an extremely common bread ingredient that is fully approved and recognized as safe by the FDA.”
  However, as confident as Subway sound that the chemical is safe, according to the Center for Science in the Public Interest, it has not been tested thoroughly enough.
  But it’s not just Subway that’s guilty of using Azodicarbonamide. Various grocery stores and restaurant breads also contain this chemical, including McDonald’s, Starbucks and Arby’s.

	- Top ingredients to avoid in commercial bread
	  Back in the day, our grandparents enjoyed a much purer diet free from the additives found in commercial breads, and they were healthier because of it. Nowadays, a lot of food available to us is filled with artificial ingredients that we don’t know much about. Here I list common ingredients found in bread that you are best to steer clear of.
		1. High Fructose Corn Syrup (HFCS) - You won’t be shocked to see that high fructose corn syrup in bread is a naughty ingredient. The sweetener – often made from genetically modified corn – is used by food manufactures because it is less expensive than sucrose (table sugar).
		2. Butylated Hydroxyanisole (BHA) - This chemical is used as a preservative in breads. It’s no wonder that commercial bread manufacturers love this one. BHA prevents breads from going rancid too soon. However, only if we knew that according to the U.S. Department of Health and Human Services 2011 Report on Carcinogens, BHA is “reasonably anticipated to be a human carcinogen.” This ingredient is also listed on California’s list of chemicals known to the state to cause cancer. It’s funny that the FDA still approves it.
		3. Potassium Bromate - Don’t be fooled by the word ‘potassium.’ You’d be better off eating a banana than consuming this chemical in your daily bread. Potassium bromate is an oxidizing agent used to “mature” bread flour, which strengthen the dough and makes it rise and boosts volume. Potassium bromate is classified as a category 2B carcinogen (possibly carcinogenic to humans) by the International Agency for Research on Cancer (IARC). Although banned for use in foods by many countries, in the USA Potassium bromate is typically used as a flour improver
		4. Partially Hydrogenated Oil - It is common knowledge now that trans fats are bad for our heart. The FDA knows this and requires bread manufacturers to list the ingredient on their nutritional information labels. However, if a food contains less than 0.5 grams of trans fat per serving, the nutrition label can legally say the product contains no trans fats all at all… I don’t know about you but many people tend to have more than one measly piece of bread at a time. Therefore they may consume an amount of trans fats that should be specified on the bread label. Trans fats are of no benefit to the consumer, except the fact that they extend the bread’s shelf life. Personally, I would prefer my bread to go moldy quicker and my heart to live longer.
		5. Caramel Coloring - Caramel coloring is used to darken the color of commercial breads to make them look all golden and rustic like they were baked fresh from Grandma’s oven. Sneaky bread makers trying to fool us. Caramel coloring actually contains certain contaminants, such as 2- and 4-methylimidazole (2- or 4-MEI), that may be produced as a result of processing. The U.S. National Toxicology Program discovered that these chemicals cause cancer in mice, and the World Health Organization considers them “possibly carcinogenic to humans.” So although it is not known whether these contaminants do cause health issues in humans, there is a possibility that they do, and therefore it best to avoid bread that contains such ingredient.
		6. Ammonium sulfate - I thought it was just my household cleaning products and hair dye that contained ammonia, but were you aware it is also be used in bread? The FDA has regarded it safe in small quantities, but there is concern over the harmful effects it can have on us if we consume it on a regular basis. Scarily enough, ammonium sulphate has been linked with issues in the gastrointestinal tract causing diarrhea and nausea.
		7. L-Cysteine - This is an amino acid which reduces the baking time of bread. It is made from human hair, duck feathers and hog hair. I can hear you gagging now. I am too. This is usually produced in China by dissolving the hair or down in acid and transported around the world as a bread softener. Can you believe we eat this stuff?
		8. Soy - Soy shows up often in bread as either soybean oil or soy lecithin. Lecithin acts as an emulsifier, keeping water and oil from separating, and preventing rancidity. Soybean oil provides fat for added flavor, richness and texture. The concern with soy-based ingredients is that they are likely to come from genetically modified soy.

	- Other ingredients that are often found in high amounts
		1. Sugar - You don’t need me to tell that excess sugar is bad for you. Even non-sweet tasting breads can contain an alarming amount of sugar. Why, you ask? Apart from providing a sweet taste, sugar pumps up the volume of breads, helps creates a finer, even texture and retain water, which gives us bread that’s more moist, tender and stays ‘fresh’ for longer.
		2. Sodium - Salt is a great ingredient for extra flavor and is fine if consumed in moderation. However, commercial breads go overboard with their salt content, meaning that many of us consume too much sodium when we dig into our sandwich. However, some breads contain less than others, so the smart thing to do is check the nutritional information labels when shopping and pick a brand with a lesser sodium content. Your heart with thank you.
		3. Refined Grain - Refined grains don’t contain any nutritional value as they have undergone a refining whitening process. This simple carbohydrates are associated with insulin resistance and high blood pressure which can cause to heart attacks. Opt for a wholemeal bread.
	- Tips for buying the best bread
		Just because the name of the bread on the package sounds super-healthy, it doesn’t mean the bread actually is. So read carefully the nutritional label and look for the less amount of ingredients in the bread as possible. Make sure that you recognize, and can pronounce the ingredients. If you see a list of various chemicals, just because you don’t recognize an ingredient name doesn’t mean it’s harmful, but still, for optimal health, it’s best to choose whole, homemade or bakery-fresh breads that you can easily identify their ingredients (flour, yeast, water, salt) as those common to bread and you won’t have to worry about additives.
		If you’re concerned about GMO ingredients, look for the term “100 percent organic” on the label. This assures that every ingredient in the product is organic and not genetically modified.
		Finally, instead of purchasing bread, why not make it yourself? Yes it requires more time and effort, but then at least you know exactly what ingredients you are putting in your body.		
-------------------------
* Looking at the needles and colorful flowers of a rosemary plant doesn’t indicate it’s amazing potential for human body. It’s been used in aromatics, cosmetics and medicine for flu and headaches, but recent studies have unveiled an amazing new use for rosemary: enhancing your mental capability and improving your memory by 75%.


	-Smelling Rosemary to Enhance Your Memory
		One might think the next huge development in mental development would be a computer chip implanted into the brain. It turns out, enhancing your memory is much easier and far less invasive, not to mention it uses completely natural methods.
		Aromatherapy is one of the most evasive forms of alternative medicine, sometimes with results backed by science and other times complete pseudo science. The truth of the matter is that the olfactory system has a direct correlation to the brain. They depend on each other to form the reality we perceive, which is why so many scholars have taken an interest in aromatherapy. You can get more information about aromatherapy and how to use essential oils to unlock their amazing healing power in my e-book Magical Aromatherapy.
		I’ll be discussing several studies on rosemary and what they’ve unveiled about the plant’s potential over recent decades, but first a historical look back will help us understand the depth of rosemary’s involvement in human history.

	- The History of Rosemary Research
		Greek mythology describes the god of beauty and love, Aphrodite, originating from the sea with rosemary draped over her body. The Middle Ages saw the frequent use during wedding ceremonies and funerals, as well as mixed into alcoholic drinks to restore vitality.
		During the late 14th century in England, known as the country’s golden age under the rule of Queen Elizabeth I, rosemary was described in Shakespeare’s Hamlet as the “herb of remembrance”. It mainly served as a memorial symbol during times of commemoration, but were humans subconsciously linking the effects of rosemary on memory?

	- What Makes Rosemary Work?
		There are several biologically active compounds within rosemary that give it therapeutic potential. Antioxidants such as rosmarinic and carnosic acid protect living cells from radiation and carcinogens, and also exhibit antimicrobial effects (according to wikipedia). Other compounds found in rosemary such as caffeic acid, camphor, rosmanol and betulinic acid all have potential to interact positively with living cells. But how does any of this come into play if we’re simply smelling the plant?

	- Smell and Memory
		There has been research linking the senses to memory, especially smell. Some people smell their father’s aftershave, their wife’s perfume, or the type of flowers growing around their childhood home and are instantly stricken with unearthed memories.
		The studies discussed below build on the connection between smell and memory in a more scientific way. Experts go beyond the psychological science and look at chemical interactions that bind smell with cognitive function. Thanks to them, a clear connection has been made, proving that rosemary’s scent can indeed make your memory stronger – by up to 75 percent.

	- The Studies
		Scientific studies on rosemary made their first major leap in 1987 when the Planta Medica journal published a study backed by four scientists on the plant’s effect on mice. They found that the levels of 1,8-cineole in the blood and locomotion capability were increased after the critters inhaled rosemary oil. Cineole, more commonly known as eucalyptol, is compound that comprises the majority of eucalyptus oil.
--------------------------------
* The mineral mixture of sodium and chlorine, more commonly known as salt, has played an integral role in the daily life of the average person. Without it, tons of culinary dishes would be rendered dull and tasteless, and French fries would never be the same. But salt goes beyond just taste, and there are several forms of salts that have their own unique benefits for your home and kitchen.
	- Benefits of Salt
		Salt might make French fries delicious, but we mustn’t forget that it’s a mineral that’s crucial to our own survival. The combination of sodium and chlorine helps a healthy balance of fluids in the brain. They also work with responsive nerves in the brain to control electrical impulses.
		Apart from health and taste, there are several other ways people use salt to enhance their lives:

		* Preserving food
		* Cleaning dishware and ovens
		* Removing odor from hands
		* Preventing mold growth
		* Extinguishing grease fires
		* Brightening laundry and removing stains
		* Prolonging plant life
		* Easing sore throat with warm salt water gargle
		* De-icing sidewalks and driveways
	- Different Types of Salt
		As you may have noticed, salt comes in all different shapes, colors and sizes. Contrary to popular belief, not all of these commercial salts are one in the same. There are differences in the texture, taste delivery and mineral content among each type.
	- Refined Salt
		This is the most familiar type of salt in kitchen cabinets and tabletops around the world. Also known as table salt, it is sodium chloride in one of the most refined forms available. This type of salt is characterized by the fine and bleached texture left after the refinement processt
		The Global Healing Center points out that during the thorough refinement process, table salt loses mineral impact and that several types of additives that may be foreign to the body are added to prevent clumping. While there are some skeptics, there isn’t solid evidence against the safety of table salt and the presence of iodine in them is a plust
		Dr. Andrew Weil states that iodine was first added to salt in the mid 1920s to address an iodine deficiency. He said that ingesting up to 1,100 micrograms of iodine each day is the safest option for adults and children ages 4 and up. It is especially important for pregnant women to nourish their developing children. The abundance of processed foods has made iodine much less prevalent in a modern diet, so iodized salt is a convenient method of delivery, as it easily fits into practically any mealt
		Himalayan Pink Salt
		This type of salt comes from the Pakistan region and grabs attention with its pink and rocky texture. The color comes from trace amounts of iron oxide, otherwise known as rust, in the salt mine it’s harvested in. However, the amount is negligible and deemed safe for consumptiont
		Because it is a naturally harvested salt with little to no refinement, there are small amounts of essential minerals such as magnesium, calcium and potassium within it. It goes nicely sprinkled on to foods and in recipes, but many people also use solidified hunks with lights inside as lamps. These holistic health lamps are said to purify and ionize the air around them.
	-Sea Salt
		Sea salt is extracted from perhaps one of the safest methods possible: the evaporation of water. According to the American Heart Association there is a miniscule amount of refinement from extraction to consumer levels when compared to table salt and several health benefits are provided when using it. It looks similar to the crystallized structure of Himalayan salt, but often a bit smaller and with more of a translucent white color. Sea salt preferred by some foodies because of its clumped texture. This allows for a more concentrated dose of flavor in each bite.
		There are some studies that suggest positive effects on the immune system, weight loss, muscle cramping and reducing cholesterol levels when combined with adequate water. Like Himalayan salt, there are trace amounts of minerals that are found within, including a notable amount of magnesium when compared to other salts.
		Some people voice concern about polluted water. If the salt was extracted from water that was contaminated in any matter, it could pose health threats. Luckily most sea salt available has to go through FDA inspection, but it still helps to be conscious of where your salt comes from.
		Further reading: read my previous article about how to use sea salt for your skin including easy recipes for sea salt body scrub and bath salt.
	-Celtic Salt
		This salt has a unique texture thanks to the small presence of water left after refinement. It’s harvested from sea water like sea salt, but in a particular area of France. Dr. Josh Axe said the 2 millennia-year-old Celtic method of collecting it allows for a well-preserved and mineral dense salt. It’s commonly identified by the slight gray color and ongoing moist feel of the crystals.
		It also contributes to balancing electrolytes and promoting better sleep. When compared to the aforementioned salts, Celtic salt is generally higher in iron and lower in sodium. This helps if you are trying to moderate your sodium intake. Nutrition specialist Janet Renee said that the advisable intake of sodium should be less than 2,300 each day.
		Not So Bad After All
		While it’s true that too much sodium is bad for health, people shouldn’t live in fear of consuming sodium moderately. Depriving yourself of the mineral could leave your body worse off than having a bit too much. Simply avoid as much as you can processed foods and try and stay mindful of your sodium intake. Due to a lack of studies, there is no definitive “healthiest salt”. The best bet for a health-conscious consumer would be to stick with the less refined salts while making sure they get ample iodine in their diet as well.
----------------------------------------
	Cauliflower is one of my favorite vegetables, and the recipe you will find below uses the cauliflower florets (but don’t throw the stem as it is edible too and can be added to soup). It is easy to make, and you can get your buffalo wings on the vegan way. The key to making good cauliflower bites is to have them crispy and golden on the outside and soft on the inside, so you will have delicious snack or appetizer.


	* Health benefits of cauliflower
		I’ve written in the past about the incredible health benefits of the cruciferous family, which cauliflower is one of them, as well as broccoli, kale and cabbage. Cauliflower is an excellent source of vitamin C, vitamin K, folate, pantothenic acid, and vitamin B6. It is a very good source of choline, dietary fiber, omega-3 fatty acids, manganese, phosphorus, and biotin. Additionally, it is a good source of vitamin B2, protein, vitamin B1, niacin, and magnesium.
		Its broad spectrum of antioxidants helps lower the risk of free radicals in our cells which cause oxidative stress which is a risk factor for development of most cancer types. And while cauliflower is not a well-studied cruciferous vegetable from a health standpoint, there are several dozen studies linking cauliflower-containing diets to cancer prevention, especially the following types of cancer: bladder cancer, breast cancer, colon cancer, prostate cancer, and ovarian cancer. For other foods that protect against cancer development read my article about the top 14 foods that protect against cancer development.
		Cauliflower is also an excellent source of vitamin K, and also contains omega 3 which are both anti-inflammatory nutrients. Like chronic oxidative stress, chronic unwanted inflammation in the body can significantly increase our risk of cancers and other chronic diseases, especially cardiovascular diseases.
		Ccauliflower contains phytonutrients that release odorous sulfur compounds when heated. This odor becomes stronger with increased cooking time. If you want to minimize odor, retain the vegetable’s crisp texture, and reduce nutrient loss, cook the cauliflower for only a short time.

	- Safety notes
		Cauliflower contains natural substances called purines. These substances can be broken down to form uric acid. Therefore excessive intake of purine containing foods is not recommended for people who suffer from purine related problems like gout and kidney stones.  Cauliflower is often referred to (as well as the rest of the family) as goitrogenic food which means food that causes enlargement of the thyroid gland. So if you have thyroid issues, you may want to limit cauliflower consumption.
	- Cauliflower Buffalo Bites
		1 head cauliflower; chopped into bite size piece
		½ cup brown rice flour (or chickpea flour)
		½ cup water
		½ tsp salt
		1 tsp. garlic powder
		1/2 teaspoon paprika (optional)
		½ cup your favorite buffalo wing sauce (store bought or homemade). Many recipes recommend Frank’s Red Hot sauce

		* Preparation
			Preheat the oven to 450F (230C). Combine the water, flour, garlic powder, salt and paprika in a bowl and stir until well combined. Coat the cauliflower pieces completely with the batter and place them on a lightly greased, non-stick baking sheet. Bake for about 15- 20 minutes (or until the tops start to get color on them), tossing half way through.
			When the cauliflower is done, remove it from the oven and gently toss it in the hot sauce mixture. Place the cauliflower bites back on the baking sheet and bake for about 5-10 minutes, or until cauliflower is crispy. Allow cauliflower to cool for 15-20 minutes before serving. You can serve it with tzaziki (see recipe here) or other favorite dip.


